apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "resource.default.name"  . }}
  namespace: {{ include "resource.default.namespace"  . }}
  labels:
    {{- include "labels.common" . | nindent 4 }}
data:
  clientid: {{ .Values.credentiald.credentialDefault.clientID | b64enc | quote }}
  clientsecret: {{ .Values.credentiald.credentialDefault.clientSecret | b64enc | quote }}
  subscriptionid: {{ .Values.credentiald.credentialDefault.subscriptionID | b64enc | quote }}
  tenantid: {{ .Values.credentiald.credentialDefault.tenantID | b64enc | quote }}
