apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "resource.default.name"  . }}
  namespace: {{ include "resource.default.namespace"  . }}
  labels:
    {{- include "labels.common" . | nindent 4 }}
data:
  clientid: {{ .Values.azureOperatorSecret.service.azure.clientid | b64enc | quote }}
  clientsecret: {{ .Values.azureOperatorSecret.service.azure.clientsecret | b64enc | quote }}
  sptenantid: {{ .Values.azureOperatorSecret.service.azure.sptenantid | b64enc | quote }}
  subscriptionid: {{ .Values.azureOperatorSecret.service.azure.subscriptionid | b64enc | quote }}
  tenantid: {{ .Values.azureOperatorSecret.service.azure.tenantid | b64enc | quote }}
