apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "resource.default.name"  . }}
  namespace: {{ include "resource.default.namespace"  . }}
  labels:
    {{- include "labels.common" . | nindent 4 }}
data:
  clientid: {{ .Values.Installation.V1.Secret.Credentiald.Azure.CredentialDefault.ClientID | b64enc | quote }}
  clientsecret: {{ .Values.Installation.V1.Secret.Credentiald.Azure.CredentialDefault.ClientSecret | b64enc | quote }}
  subscriptionid: {{ .Values.Installation.V1.Secret.Credentiald.Azure.CredentialDefault.SubscriptionID | b64enc | quote }}
  tenantid: {{ .Values.Installation.V1.Secret.Credentiald.Azure.CredentialDefault.TenantID | b64enc | quote }}
