apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "resource.default.name"  . }}
  namespace: {{ include "resource.default.namespace"  . }}
  labels:
    {{- include "labels.common" . | nindent 4 }}
data:
  clientID: {{ .Values.azureSecret.service.azure.clientID | b64enc | quote }}
  clientSecret: {{ .Values.azureSecret.service.azure.clientSecret | b64enc | quote }}
  subscriptionID: {{ .Values.azureSecret.service.azure.subscriptionID | b64enc | quote }}
  tenantID: {{ .Values.azureSecret.service.azure.tenantID | b64enc | quote }}
