apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "resource.default.name"  . }}
  namespace: {{ include "resource.default.namespace"  . }}
  labels:
    {{- include "labels.common" . | nindent 4 }}
data:
  clientid: {{ .Values.Installation.V1.Secret.Credentiald.Azure.CredentialDefault.ClientID }}
  clientsecret: {{ .Values.Installation.V1.Secret.Credentiald.Azure.CredentialDefault.ClientSecret }}
  subscriptionid: {{ .Values.Installation.V1.Secret.Credentiald.Azure.CredentialDefault.SubscriptionID }}
  tenantid: {{ .Values.Installation.V1.Secret.Credentiald.Azure.CredentialDefault.TenantID }}
