---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: {{ include "resource.default.name" . }}
  namespace: {{ include "resource.default.namespace" . }}
  annotations:
    cert-manager.io/inject-ca-from: {{ include "resource.default.namespace" . }}/{{ include "resource.default.name" . }}-certificates
  labels:
  {{- include "labels.common" . | nindent 4 }}
webhooks:
- name: mutate.azureclusters.create.{{ include "resource.default.name" . }}.giantswarm.io
  failurePolicy: Fail
  clientConfig:
    service:
      name: {{ include "resource.default.name" . }}
      namespace: {{ include "resource.default.namespace" . }}
      path: /mutate/azurecluster/create
    caBundle: Cg==
  rules:
    - apiGroups: ["infrastructure.cluster.x-k8s.io"]
      resources:
        - "azureclusters"
      apiVersions:
        - "v1alpha3"
      operations:
        - CREATE
  sideEffects: None
  admissionReviewVersions: ["v1", "v1beta1"]
- name: mutate.azureclusters.update.{{ include "resource.default.name" . }}.giantswarm.io
  failurePolicy: Fail
  clientConfig:
    service:
      name: {{ include "resource.default.name" . }}
      namespace: {{ include "resource.default.namespace" . }}
      path: /mutate/azurecluster/update
    caBundle: Cg==
  rules:
    - apiGroups: ["infrastructure.cluster.x-k8s.io"]
      resources:
        - "azureclusters"
      apiVersions:
        - "v1alpha3"
      operations:
        - UPDATE
  sideEffects: None
  admissionReviewVersions: ["v1", "v1beta1"]
- name: mutate.azuremachines.create.{{ include "resource.default.name" . }}.giantswarm.io
  failurePolicy: Fail
  clientConfig:
    service:
      name: {{ include "resource.default.name" . }}
      namespace: {{ include "resource.default.namespace" . }}
      path: /mutate/azuremachine/create
    caBundle: Cg==
  rules:
    - apiGroups: ["infrastructure.cluster.x-k8s.io"]
      resources:
        - "azuremachines"
      apiVersions:
        - "v1alpha3"
      operations:
        - CREATE
  sideEffects: None
  admissionReviewVersions: ["v1", "v1beta1"]
- name: mutate.azuremachines.update.{{ include "resource.default.name" . }}.giantswarm.io
  failurePolicy: Fail
  clientConfig:
    service:
      name: {{ include "resource.default.name" . }}
      namespace: {{ include "resource.default.namespace" . }}
      path: /mutate/azuremachine/update
    caBundle: Cg==
  rules:
    - apiGroups: ["infrastructure.cluster.x-k8s.io"]
      resources:
        - "azuremachines"
      apiVersions:
        - "v1alpha3"
      operations:
        - UPDATE
  sideEffects: None
  admissionReviewVersions: ["v1", "v1beta1"]
- name: mutate.azuremachinepools.create.{{ include "resource.default.name" . }}.giantswarm.io
  failurePolicy: Fail
  clientConfig:
    service:
      name: {{ include "resource.default.name" . }}
      namespace: {{ include "resource.default.namespace" . }}
      path: /mutate/azuremachinepool/create
    caBundle: Cg==
  rules:
    - apiGroups: ["exp.infrastructure.cluster.x-k8s.io"]
      resources:
        - "azuremachinepools"
      apiVersions:
        - "v1alpha3"
      operations:
        - CREATE
  sideEffects: None
  admissionReviewVersions: ["v1", "v1beta1"]
- name: mutate.azuremachinepools.update.{{ include "resource.default.name" . }}.giantswarm.io
  failurePolicy: Fail
  clientConfig:
    service:
      name: {{ include "resource.default.name" . }}
      namespace: {{ include "resource.default.namespace" . }}
      path: /mutate/azuremachinepool/update
    caBundle: Cg==
  rules:
    - apiGroups: ["exp.infrastructure.cluster.x-k8s.io"]
      resources:
        - "azuremachinepools"
      apiVersions:
        - "v1alpha3"
      operations:
        - UPDATE
  sideEffects: None
  admissionReviewVersions: ["v1", "v1beta1"]
- name: mutate.clusters.create.{{ include "resource.default.name" . }}.giantswarm.io
  failurePolicy: Fail
  clientConfig:
    service:
      name: {{ include "resource.default.name" . }}
      namespace: {{ include "resource.default.namespace" . }}
      path: /mutate/cluster/create
    caBundle: Cg==
  rules:
    - apiGroups: ["cluster.x-k8s.io"]
      resources:
        - "clusters"
      apiVersions:
        - "v1alpha3"
      operations:
        - CREATE
  sideEffects: None
  admissionReviewVersions: ["v1", "v1beta1"]
- name: mutate.clusters.update.{{ include "resource.default.name" . }}.giantswarm.io
  failurePolicy: Fail
  clientConfig:
    service:
      name: {{ include "resource.default.name" . }}
      namespace: {{ include "resource.default.namespace" . }}
      path: /mutate/cluster/update
    caBundle: Cg==
  rules:
    - apiGroups: ["cluster.x-k8s.io"]
      resources:
        - "clusters"
      apiVersions:
        - "v1alpha3"
      operations:
        - UPDATE
  sideEffects: None
  admissionReviewVersions: ["v1", "v1beta1"]
- name: mutate.machinepools.create.{{ include "resource.default.name" . }}.giantswarm.io
  failurePolicy: Fail
  clientConfig:
    service:
      name: {{ include "resource.default.name" . }}
      namespace: {{ include "resource.default.namespace" . }}
      path: /mutate/machinepool/create
    caBundle: Cg==
  rules:
    - apiGroups: ["exp.cluster.x-k8s.io"]
      resources:
        - "machinepools"
      apiVersions:
        - "v1alpha3"
      operations:
        - CREATE
  sideEffects: None
  admissionReviewVersions: ["v1", "v1beta1"]
- name: mutate.machinepools.update.{{ include "resource.default.name" . }}.giantswarm.io
  failurePolicy: Fail
  clientConfig:
    service:
      name: {{ include "resource.default.name" . }}
      namespace: {{ include "resource.default.namespace" . }}
      path: /mutate/machinepool/update
    caBundle: Cg==
  rules:
    - apiGroups: ["exp.cluster.x-k8s.io"]
      resources:
        - "machinepools"
      apiVersions:
        - "v1alpha3"
      operations:
        - UPDATE
  sideEffects: None
  admissionReviewVersions: ["v1", "v1beta1"]
- name: mutate.sparks.create.{{ include "resource.default.name" . }}.giantswarm.io
  failurePolicy: Fail
  clientConfig:
    service:
      name: {{ include "resource.default.name" . }}
      namespace: {{ include "resource.default.namespace" . }}
      path: /mutate/spark/create
    caBundle: Cg==
  rules:
    - apiGroups: ["core.giantswarm.io"]
      resources:
        - "sparks"
      apiVersions:
        - "v1alpha1"
      operations:
        - CREATE
  sideEffects: None
  admissionReviewVersions: ["v1", "v1beta1"]
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: {{ include "resource.default.name" . }}
  namespace: {{ include "resource.default.namespace" . }}
  annotations:
    cert-manager.io/inject-ca-from: {{ include "resource.default.namespace" . }}/{{ include "resource.default.name" . }}-certificates
  labels:
  {{- include "labels.common" . | nindent 4 }}
webhooks:
  - name: validate.azureconfigs.{{ include "resource.default.name" . }}.giantswarm.io
    failurePolicy: Fail
    clientConfig:
      service:
        name: {{ include "resource.default.name" . }}
        namespace: {{ include "resource.default.namespace" . }}
        path: /validate/azureconfig/update
      caBundle: Cg==
    rules:
      - apiGroups: ["provider.giantswarm.io"]
        resources:
          - "azureconfigs"
        apiVersions:
          - "v1alpha1"
        operations:
          - UPDATE
    sideEffects: None
    admissionReviewVersions: ["v1", "v1beta1"]
  - name: validate.azureclusterconfigs.{{ include "resource.default.name" . }}.giantswarm.io
    failurePolicy: Fail
    clientConfig:
      service:
        name: {{ include "resource.default.name" . }}
        namespace: {{ include "resource.default.namespace" . }}
        path: /validate/azureclusterconfig/update
      caBundle: Cg==
    rules:
      - apiGroups: ["core.giantswarm.io"]
        resources:
          - "azureclusterconfigs"
        apiVersions:
          - "v1alpha1"
        operations:
          - UPDATE
    sideEffects: None
    admissionReviewVersions: ["v1", "v1beta1"]
  - name: validate.azuremachinepools.create.{{ include "resource.default.name" . }}.giantswarm.io
    failurePolicy: Fail
    clientConfig:
      service:
        name: {{ include "resource.default.name" . }}
        namespace: {{ include "resource.default.namespace" . }}
        path: /validate/azuremachinepool/create
      caBundle: Cg==
    rules:
      - apiGroups: ["exp.infrastructure.cluster.x-k8s.io"]
        resources:
          - "azuremachinepools"
        apiVersions:
          - "v1alpha3"
        operations:
          - CREATE
    sideEffects: None
    admissionReviewVersions: ["v1", "v1beta1"]
  - name: validate.azuremachinepools.update.{{ include "resource.default.name" . }}.giantswarm.io
    failurePolicy: Fail
    clientConfig:
      service:
        name: {{ include "resource.default.name" . }}
        namespace: {{ include "resource.default.namespace" . }}
        path: /validate/azuremachinepool/update
      caBundle: Cg==
    rules:
      - apiGroups: ["exp.infrastructure.cluster.x-k8s.io"]
        resources:
          - "azuremachinepools"
        apiVersions:
          - "v1alpha3"
        operations:
          - UPDATE
    sideEffects: None
    admissionReviewVersions: ["v1", "v1beta1"]
  - name: validate.azureclusters.create.{{ include "resource.default.name" . }}.giantswarm.io
    failurePolicy: Fail
    clientConfig:
      service:
        name: {{ include "resource.default.name" . }}
        namespace: {{ include "resource.default.namespace" . }}
        path: /validate/azurecluster/create
      caBundle: Cg==
    rules:
      - apiGroups: ["infrastructure.cluster.x-k8s.io"]
        resources:
          - "azureclusters"
        apiVersions:
          - "v1alpha3"
        operations:
          - CREATE
    sideEffects: None
    admissionReviewVersions: ["v1", "v1beta1"]
  - name: validate.azureclusters.update.{{ include "resource.default.name" . }}.giantswarm.io
    failurePolicy: Fail
    clientConfig:
      service:
        name: {{ include "resource.default.name" . }}
        namespace: {{ include "resource.default.namespace" . }}
        path: /validate/azurecluster/update
      caBundle: Cg==
    rules:
      - apiGroups: ["infrastructure.cluster.x-k8s.io"]
        resources:
          - "azureclusters"
        apiVersions:
          - "v1alpha3"
        operations:
          - UPDATE
    sideEffects: None
    admissionReviewVersions: ["v1", "v1beta1"]
  - name: validate.azuremachines.create.{{ include "resource.default.name" . }}.giantswarm.io
    failurePolicy: Fail
    clientConfig:
      service:
        name: {{ include "resource.default.name" . }}
        namespace: {{ include "resource.default.namespace" . }}
        path: /validate/azuremachine/create
      caBundle: Cg==
    rules:
      - apiGroups: ["infrastructure.cluster.x-k8s.io"]
        resources:
          - "azuremachines"
        apiVersions:
          - "v1alpha3"
        operations:
          - CREATE
    sideEffects: None
    admissionReviewVersions: ["v1", "v1beta1"]
  - name: validate.azuremachines.update.{{ include "resource.default.name" . }}.giantswarm.io
    failurePolicy: Fail
    clientConfig:
      service:
        name: {{ include "resource.default.name" . }}
        namespace: {{ include "resource.default.namespace" . }}
        path: /validate/azuremachine/update
      caBundle: Cg==
    rules:
      - apiGroups: ["infrastructure.cluster.x-k8s.io"]
        resources:
          - "azuremachines"
        apiVersions:
          - "v1alpha3"
        operations:
          - UPDATE
    sideEffects: None
    admissionReviewVersions: ["v1", "v1beta1"]
  - name: validate.cluster.create.{{ include "resource.default.name" . }}.giantswarm.io
    failurePolicy: Fail
    clientConfig:
      service:
        name: {{ include "resource.default.name" . }}
        namespace: {{ include "resource.default.namespace" . }}
        path: /validate/cluster/create
      caBundle: Cg==
    rules:
      - apiGroups: ["cluster.x-k8s.io"]
        resources:
          - "clusters"
        apiVersions:
          - "v1alpha3"
        operations:
          - CREATE
    sideEffects: None
    admissionReviewVersions: ["v1", "v1beta1"]
  - name: validate.cluster.update.{{ include "resource.default.name" . }}.giantswarm.io
    failurePolicy: Fail
    clientConfig:
      service:
        name: {{ include "resource.default.name" . }}
        namespace: {{ include "resource.default.namespace" . }}
        path: /validate/cluster/update
      caBundle: Cg==
    rules:
      - apiGroups: ["cluster.x-k8s.io"]
        resources:
          - "clusters"
        apiVersions:
          - "v1alpha3"
        operations:
          - UPDATE
    sideEffects: None
    admissionReviewVersions: ["v1", "v1beta1"]
  - name: validate.machinepools.create.{{ include "resource.default.name" . }}.giantswarm.io
    failurePolicy: Fail
    clientConfig:
      service:
        name: {{ include "resource.default.name" . }}
        namespace: {{ include "resource.default.namespace" . }}
        path: /validate/machinepool/create
      caBundle: Cg==
    rules:
      - apiGroups: ["exp.cluster.x-k8s.io"]
        resources:
          - "machinepools"
        apiVersions:
          - "v1alpha3"
        operations:
          - CREATE
    sideEffects: None
    admissionReviewVersions: ["v1", "v1beta1"]
  - name: validate.machinepools.update.{{ include "resource.default.name" . }}.giantswarm.io
    failurePolicy: Fail
    clientConfig:
      service:
        name: {{ include "resource.default.name" . }}
        namespace: {{ include "resource.default.namespace" . }}
        path: /validate/machinepool/update
      caBundle: Cg==
    rules:
      - apiGroups: ["exp.cluster.x-k8s.io"]
        resources:
          - "machinepools"
        apiVersions:
          - "v1alpha3"
        operations:
          - UPDATE
    sideEffects: None
    admissionReviewVersions: ["v1", "v1beta1"]
