apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: {{ include "resource.default.name" . }}
  namespace: {{ include "resource.default.namespace" . }}
  annotations:
    cert-manager.io/inject-ca-from: {{ include "resource.default.namespace" . }}/{{ include "resource.default.name" . }}-certificates
  labels:
  {{- include "labels.common" . | nindent 4 }}
webhooks:
  - name: azureconfigs.{{ include "resource.default.name" . }}.giantswarm.io
    failurePolicy: Fail
    clientConfig:
      service:
        name: {{ include "resource.default.name" . }}
        namespace: {{ include "resource.default.namespace" . }}
        path: /azureconfig/update
      caBundle: Cg==
    rules:
      - apiGroups: ["provider.giantswarm.io"]
        resources:
          - "azureconfigs"
        apiVersions:
          - "v1alpha1"
        operations:
          - UPDATE
    sideEffects: None
    admissionReviewVersions: ["v1", "v1beta1"]
  - name: azureclusterconfigs.{{ include "resource.default.name" . }}.giantswarm.io
    failurePolicy: Fail
    clientConfig:
      service:
        name: {{ include "resource.default.name" . }}
        namespace: {{ include "resource.default.namespace" . }}
        path: /azureclusterconfig/update
      caBundle: Cg==
    rules:
      - apiGroups: ["core.giantswarm.io"]
        resources:
          - "azureclusterconfigs"
        apiVersions:
          - "v1alpha1"
        operations:
          - UPDATE
    sideEffects: None
    admissionReviewVersions: ["v1", "v1beta1"]
  - name: azuremachinepools.create.{{ include "resource.default.name" . }}.giantswarm.io
    failurePolicy: Fail
    clientConfig:
      service:
        name: {{ include "resource.default.name" . }}
        namespace: {{ include "resource.default.namespace" . }}
        path: /azuremachinepool/create
      caBundle: Cg==
    rules:
      - apiGroups: ["exp.infrastructure.cluster.x-k8s.io"]
        resources:
          - "azuremachinepools"
        apiVersions:
          - "v1alpha3"
        operations:
          - CREATE
    sideEffects: None
    admissionReviewVersions: ["v1", "v1beta1"]
  - name: azuremachinepools.update.{{ include "resource.default.name" . }}.giantswarm.io
    failurePolicy: Fail
    clientConfig:
      service:
        name: {{ include "resource.default.name" . }}
        namespace: {{ include "resource.default.namespace" . }}
        path: /azuremachinepool/update
      caBundle: Cg==
    rules:
      - apiGroups: ["exp.infrastructure.cluster.x-k8s.io"]
        resources:
          - "azuremachinepools"
        apiVersions:
          - "v1alpha3"
        operations:
          - UPDATE
    sideEffects: None
    admissionReviewVersions: ["v1", "v1beta1"]
  - name: azureclusters.update.{{ include "resource.default.name" . }}.giantswarm.io
    failurePolicy: Fail
    clientConfig:
      service:
        name: {{ include "resource.default.name" . }}
        namespace: {{ include "resource.default.namespace" . }}
        path: /azurecluster/update
      caBundle: Cg==
    rules:
      - apiGroups: ["infrastructure.cluster.x-k8s.io"]
        resources:
          - "azureclusters"
        apiVersions:
          - "v1alpha3"
        operations:
          - UPDATE
    sideEffects: None
    admissionReviewVersions: ["v1", "v1beta1"]
  - name: azuremachines.update.{{ include "resource.default.name" . }}.giantswarm.io
    failurePolicy: Fail
    clientConfig:
      service:
        name: {{ include "resource.default.name" . }}
        namespace: {{ include "resource.default.namespace" . }}
        path: /azuremachine/update
      caBundle: Cg==
    rules:
      - apiGroups: ["infrastructure.cluster.x-k8s.io"]
        resources:
          - "azuremachines"
        apiVersions:
          - "v1alpha3"
        operations:
          - UPDATE
    sideEffects: None
    admissionReviewVersions: ["v1", "v1beta1"]
  - name: cluster.update.{{ include "resource.default.name" . }}.giantswarm.io
    failurePolicy: Fail
    clientConfig:
      service:
        name: {{ include "resource.default.name" . }}
        namespace: {{ include "resource.default.namespace" . }}
        path: /cluster/update
      caBundle: Cg==
    rules:
      - apiGroups: ["cluster.x-k8s.io"]
        resources:
          - "clusters"
        apiVersions:
          - "v1alpha3"
        operations:
          - UPDATE
    sideEffects: None
    admissionReviewVersions: ["v1", "v1beta1"]
