image:
  name: "giantswarm/azure-admission-controller"
  tag: "[[ .Version ]]"

project:
  branch: "[[ .Branch ]]"
  commit: "[[ .SHA ]]"

pod:
  user:
    id: 1000
  group:
    id: 1000

workloadCluster:
  kubernetes:
    api:
      endpointBase: k8s.test.westeurope.azure.gigantic.io

azure:
  location: westeurope

registry:
  domain: docker.io

podDisruptionBudget:
  enabled: true
  minAvailable: 1

verticalPodAutoscaler:
  enabled: true
