image:
  name: "giantswarm/azure-admission-controller"
  tag: "[[ .Version ]]"

project:
  branch: "[[ .Branch ]]"
  commit: "[[ .SHA ]]"

workloadCluster:
  kubernetes:
    api:
      endpointBase: k8s.test.westeurope.azure.gigantic.io

provider:
  azure:
    location: westeurope

registry:
  domain: docker.io

credentiald:
  credentialDefault:
    clientID: ""
    clientSecret: ""
    tenantID: ""
    subscriptionID: ""
