project:
  branch: "[[ .Branch ]]"
  commit: "[[ .SHA ]]"

image:
  name: "giantswarm/azure-admission-controller"
  tag: "[[ .Version ]]"

azure:
  location: ""

azureOperatorSecret:
  service:
    azure:
      clientid: ""
      clientsecret: ""
      sptenantid: ""
      subscriptionid: ""
      tenantid: ""

cluster:
  baseDomain: ""

registry:
  domain: ""
